const codes = [
  ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal', 'Backspace'],
  ['Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash', 'Delete'],
  ['CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter'],
  ['ShiftLeft', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp' , 'ShiftRight'],
  ['ControlLeft', 'MetaLeft', 'AltLeft', 'Space', 'AltRight', 'ArrowLeft', 'ArrowDown', 'ArrowRight', 'ControlRight'],
];

const dataEng = {
  ArrowDown: ['▼', '▼', '▼', '▼'],
  ArrowLeft: ['◄', '◄', '◄', '◄'],
  ArrowRight: ['►', '►', '►', '►'],
  ArrowUp: ['▲', '▲', '▲', '▲'],
  Backquote: ['`', '~', '`', '~'],
  Backslash: ['\\', '|', '\\', '|'],
  BracketLeft: ['[', '{', '[', '{'],
  BracketRight: [']', '}', ']', '}'],
  Comma: [',', '<', ',', '<'],
  Digit0: ['0', ')', '0', ')'],
  Digit1: ['1', '!', '1', '!'],
  Digit2: ['2', '@', '2', '@'],
  Digit3: ['3', '#', '3', '#'],
  Digit4: ['4', '$', '4', '$'],
  Digit5: ['5', '%', '5', '%'],
  Digit6: ['6', '^', '6', '^'],
  Digit7: ['7', '&', '7', '&'],
  Digit8: ['8', '*', '8', '*'],
  Digit9: ['9', '(', '9', '('],
  Equal: ['=', '+', '=', '+'],
  KeyA: ['a', 'A', 'A', 'a'],
  KeyB: ['b', 'B', 'B', 'b'],
  KeyC: ['c', 'C', 'C', 'c'],
  KeyD: ['d', 'D', 'D', 'd'],
  KeyE: ['e', 'E', 'E', 'e'],
  KeyF: ['f', 'F', 'F', 'f'],
  KeyG: ['g', 'G', 'G', 'g'],
  KeyH: ['h', 'H', 'H', 'h'],
  KeyI: ['i', 'I', 'I', 'i'],
  KeyJ: ['j', 'J', 'J', 'j'],
  KeyK: ['k', 'K', 'K', 'k'],
  KeyL: ['l', 'L', 'L', 'l'],
  KeyM: ['m', 'M', 'M', 'm'],
  KeyN: ['n', 'N', 'N', 'n'],
  KeyO: ['o', 'O', 'O', 'o'],
  KeyP: ['p', 'P', 'P', 'p'],
  KeyQ: ['q', 'Q', 'Q', 'q'],
  KeyR: ['r', 'R', 'R', 'r'],
  KeyS: ['s', 'S', 'S', 's'],
  KeyT: ['t', 'T', 'T', 't'],
  KeyU: ['u', 'U', 'U', 'u'],
  KeyV: ['v', 'V', 'V', 'v'],
  KeyW: ['w', 'W', 'W', 'w'],
  KeyX: ['x', 'X', 'X', 'x'],
  KeyY: ['y', 'Y', 'Y', 'y'],
  KeyZ: ['z', 'Z', 'Z', 'z'],
  Minus: ['-', '_', '-', '_'],
  Period: ['.', '>', '.', '>'],
  Quote: ["'", '"', "'", '"'],
  Semicolon: [';', ':', ';', ':'],
  Slash: ['/', '?', '/', '?'],
  Space: [' ', ' ', ' ', ' '],
  AltLeft: ['Alt', 'Alt', 'Alt', 'Alt'],
  AltRight: ['Alt', 'Alt', 'Alt', 'Alt'],
  Backspace: ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
  CapsLock: ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  ControlLeft: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ControlRight: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  Delete: ['Del', 'Del', 'Del', 'Del'],
  Enter: ['Enter', 'Enter', 'Enter', 'Enter'],
  MetaLeft: ['Win', 'Win', 'Win', 'Win'],
  ShiftLeft: ['Shift', 'Shift', 'Shift', 'Shift'],
  ShiftRight: ['Shift', 'Shift', 'Shift', 'Shift'],
  Tab: ['Tab', 'Tab', 'Tab', 'Tab'],
};

const dataRus = {
  ArrowDown: ['▼', '▼', '▼', '▼'],
  ArrowLeft: ['◄', '◄', '◄', '◄'],
  ArrowRight: ['►', '►', '►', '►'],
  ArrowUp: ['▲', '▲', '▲', '▲'],
  Backslash: ['\\', '/', '\\', '/'],
  BracketLeft: ['х', 'Х', 'Х', 'х'],
  BracketRight: ['ъ', 'Ъ', 'Ъ', 'ъ'],
  Comma: ['б', 'Б', 'Б', 'б'],
  Backquote: ['ё', 'Ё', 'Ё', 'ё'],
  Digit0: ['0', ')', '0', ')'],
  Digit1: ['1', '!', '1', '!'],
  Digit2: ['2', '"', '2', '"'],
  Digit3: ['3', '№', '3', '№'],
  Digit4: ['4', ';', '4', ';'],
  Digit5: ['5', '%', '5', '%'],
  Digit6: ['6', ':', '6', ':'],
  Digit7: ['7', '?', '7', '?'],
  Digit8: ['8', '*', '8', '*'],
  Digit9: ['9', '(', '9', '('],
  Equal: ['=', '+', '=', '+'],
  KeyA: ['ф', 'Ф', 'Ф', 'ф'],
  KeyB: ['и', 'И', 'И', 'и'],
  KeyC: ['с', 'С', 'С', 'с'],
  KeyD: ['в', 'В', 'В', 'в'],
  KeyE: ['у', 'У', 'У', 'у'],
  KeyF: ['а', 'А', 'А', 'а'],
  KeyG: ['п', 'П', 'П', 'п'],
  KeyH: ['р', 'Р', 'Р', 'р'],
  KeyI: ['ш', 'Ш', 'Ш', 'ш'],
  KeyJ: ['о', 'О', 'О', 'о'],
  KeyK: ['л', 'Л', 'Л', 'л'],
  KeyL: ['д', 'Д', 'Д', 'д'],
  KeyM: ['ь', 'Ь', 'Ь', 'ь'],
  KeyN: ['т', 'Т', 'Т', 'т'],
  KeyO: ['щ', 'Щ', 'Щ', 'щ'],
  KeyP: ['з', 'З', 'З', 'з'],
  KeyQ: ['й', 'Й', 'Й', 'й'],
  KeyR: ['к', 'К', 'К', 'к'],
  KeyS: ['ы', 'Ы', 'Ы', 'ы'],
  KeyT: ['е', 'Е', 'Е', 'е'],
  KeyU: ['г', 'Г', 'Г', 'г'],
  KeyV: ['м', 'М', 'М', 'м'],
  KeyW: ['ц', 'Ц', 'Ц', 'ц'],
  KeyX: ['ч', 'Ч', 'Ч', 'ч'],
  KeyY: ['н', 'Н', 'Н', 'н'],
  KeyZ: ['я', 'Я', 'Я', 'я'],
  Minus: ['-', '_', '-', '_'],
  Period: ['ю', 'Ю', 'Ю', 'ю'],
  Quote: ['э', 'Э', 'Э', 'э'],
  Semicolon: ['ж', 'Ж', 'Ж', 'ж'],
  Slash: ['.', ',', '.', ','],
  Space: [' ', ' ', ' ', ' '],
  AltLeft: ['Alt', 'Alt', 'Alt', 'Alt'],
  AltRight: ['Alt', 'Alt', 'Alt', 'Alt'],
  Backspace: ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
  CapsLock: ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  ControlLeft: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ControlRight: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  Delete: ['Del', 'Del', 'Del', 'Del'],
  Enter: ['Enter', 'Enter', 'Enter', 'Enter'],
  MetaLeft: ['Win', 'Win', 'Win', 'Win'],
  ShiftLeft: ['Shift', 'Shift', 'Shift', 'Shift'],
  ShiftRight: ['Shift', 'Shift', 'Shift', 'Shift'],
  Tab: ['Tab', 'Tab', 'Tab', 'Tab'],
}

export { codes, dataEng, dataRus };